[book]
authors = ["Geert Mulders", "Daan van Berkel"]
language = "en"
multilingual = false
src = "src"
title = "50 shades of FizzBuzz"

[output.html]
mathjax-support = true
additional-css = ["custom.css"]
